FROM ubuntu:18.04
MAINTAINER Chieh

RUN apt-get update
RUN apt-get install -y net-tools
RUN apt-get install -y git curl
RUN curl -sL https://deb.nodesource.com/setup_13.x | bash - && apt-get install -y nodejs
RUN apt-get install -y vim
